#!/bin/bash
#PBS -l select=1:ncpus=10:mpiprocs=4:mem=15gb
#PBS -P CSCI1166
#PBS -q serial
#PBS -l walltime=10:00:00
#PBS -o /mnt/lustre/users/fredelinghuys/TCP_Adv_Int/TCP_Adv_Int_5/TCP_Adv_Int_5.out
#PBS -e /mnt/lustre/users/fredelinghuys/TCP_Adv_Int/TCP_Adv_Int_5/TCP_Adv_Int_5.err
#PBS -m abe
#PBS -M cobus.redelinghuys@up.ac.za
ulimit -s unlimited
 
cd /mnt/lustre/users/fredelinghuys/TCP_Adv_Int/TCP_Adv_Int_5
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE
 
# Run program
module load chpc/python/3.7.0
source visualizerenv/bin/activate
module load chpc/java/17.0.2
make
tar -cvf TCP_Adv_Int_5.tar ./
