main:
	make -C "equilateral/Best/" || true
	make -C "equilateral/Default/" || true
	make -C "equilateral/Worst/" || true
	make -C "equilateral/RNG/" || true
	make -C "isosceles/Best/" || true
	make -C "isosceles/Default/" || true
	make -C "isosceles/Worst/" || true
	make -C "isosceles/RNG/" || true
	make -C "not/Best/" || true
	make -C "not/Default/" || true
	make -C "not/Worst/" || true
	make -C "not/RNG/" || true
	make -C "scalene/Best/" || true
	make -C "scalene/Default/" || true
	make -C "scalene/Worst/" || true
	make -C "scalene/RNG/" || true