#!/bin/bash
#PBS -l select=1:ncpus=10:mpiprocs=4:mem=20gb
#PBS -P CSCI1166
#PBS -q serial
#PBS -l walltime=03:00:00
#PBS -o /mnt/lustre/users/fredelinghuys/Package8_4/Package8_4.out
#PBS -e /mnt/lustre/users/fredelinghuys/Package8_4/Package8_4.err
#PBS -m abe
#PBS -M cobus.redelinghuys@up.ac.za
ulimit -s unlimited
 
cd /mnt/lustre/users/fredelinghuys/Package8_4
nproc=`cat $PBS_NODEFILE | wc -l`
echo nproc is $nproc
cat $PBS_NODEFILE
 
# Run program
module load chpc/python/3.7.0
source visualizerenv/bin/activate
module load chpc/java/17.0.2
make
tar -cvf Package8_4.tar ./
